source 'https://cdn.cocoapods.org/'
source 'https://github.com/volcengine/volcengine-specs.git'

def app_pod
  # 场景化源码
  # Scene source code
  pod 'Login', :path => '../veRTC_Demo_iOS/APP/Login'
  pod 'VoiceChatDemo', :path => '../veRTC_Demo_iOS/APP/VoiceChatDemo'
end


def core_pod
  # 基础组件
  # Basic components
  pod 'Core', :path => '../veRTC_Demo_iOS/Core'
end

def sdk_pod
  # 依赖 SDK
  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  pod 'VolcEngineRTC'
end

target 'veRTC_Demo' do
  sdk_pod
  core_pod
  app_pod
end



