mysql_dsn: "root:bytedance@tcp(mysql_server:3306)/rtc_demo_db?parseTime=true&loc=Local"
redis_addr: "redis_server:6379"
redis_password: ""
addr: "0.0.0.0"
port: "18080"
server_url: "http://your_ip:18080/rtc_demo/rtm"
cs_app_id: "your_app_id"
cs_app_key: "your_app_key"
cs_experience_time: 20
volc_ak: "your_ak"
volc_sk: "your_sk"

